# Imports

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys
import os

import numpy as np
import pandas as pd

In [46]:
sys.path.append(os.getcwd() + '/refi')
import retirement_analysis as ra
import constants
import asset
import consumption
#import inflation
import portfolio as pf

import series

# Constants

In [38]:
initial_balance = 400000
initial_cpi = 275
initial_age = 30
initial_deferral = 19500
retirement_age = 60
retirement_consumption = 75000
death_age = 100

In [48]:
num_scenarios = 3
num_years = death_age - initial_age + 1

In [40]:
geo_mean_equity_return = .065
geo_mean_bond_return = .035
geo_mean_cash_return = .002

geo_mean_inflation = .02


# Portfolio

In [57]:
equity = series.StaticSeries(num_years, geo_mean_equity_return)
bond = series.StaticSeries(num_years, geo_mean_bond_return)
cash = series.StaticSeries(num_years, geo_mean_cash_return)

In [58]:
assets = [equity, bond, cash]
balance = initial_balance

In [59]:
glidepath = constants.fidelity_glidepath

In [60]:
portfolio = pf.Portfolio(assets, glidepath, balance)

# Inflation Scenario

In [147]:
# inflation_scenario = series.StaticSeries(num_years, geo_mean_inflation)
inflation_scenario = series.PositiveGaussianSeries(num_years, mean=geo_mean_inflation, std_dev=.005)

In [226]:
inflation_scenario.history

array([0.01971003, 0.01310406, 0.00848944, 0.01611065, 0.01859087,
       0.02586759, 0.02194343, 0.01006315, 0.02258356,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan])

In [225]:
inflation_scenario.step()

In [195]:
cpi_scenario = series.StaticGrowthSeries(initial_value=100, growth_series=inflation_scenario)

In [230]:
cpi_scenario.history.shape

(72,)

In [232]:
inflation_scenario.history.shape

(71,)

In [227]:
cpi_scenario.period

8

In [228]:
cpi_scenario.step()

In [229]:
cpi_scenario.history

array([100.        , 101.97100297, 103.30723725, 104.18425743,
       105.86273371, 107.83081352, 110.62013665, 113.04752212,
       114.18513653, 116.76384318,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,       

In [ ]:
cpi

In [234]:
num_years = 50
mean_inflation = .02
std_dev_inflation = .005
inflation_scenario = series.PositiveGaussianSeries(num_years, mean=mean_inflation, std_dev=std_dev_inflation)
consumption_scenario = series.StaticGrowthSeries(initial_value=10000, growth_series=inflation_scenario)

True

True

True

True

IndexError: Final period 49 reached, cannot step further.

True

Cannot get_next_value: cannot calculate value for period 3 when growth_series is only at period 1.


True

True

True

True

# Consumption Scenario

In [139]:
consumption_scenario = consumption.StaticRetirementConsumption(initial_tgt_consumption=retirement_consumption, 
                                                      initial_cpi=initial_cpi, initial_age, retirement_age))

In [67]:
consumption_series = series.StaticGrowthSeries(initial_value=100, growth_series=inflation_scenario)

In [68]:
consumption_series.history

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan])

In [78]:
inflation_scenario.step()

In [79]:
inflation_scenario.history

array([0.02, 0.02,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan])

In [81]:
consumption_series.step()

In [82]:
consumption_series.history

array([100.    , 102.    , 104.04  , 106.1208,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan])

In [142]:
consumption_scenario.print_history()

Historical Target Consumption:
[75000. 86250.]


In [143]:
consumption_scenario.step(.15)

In [118]:
np.clip(-1, a_min=-.9999, a_max=None)

-0.9999